spring:
  profiles:
    active: local

# local 환경
---
spring:
  profiles: local
  thymeleaf: #Thymeleaf 설정 #JSP와 같이 사용시 뷰 구분을 위해 컨트롤러가 뷰 이름을 반환시 thymeleaf/ 로 시작하면 타임리프로 처리하도록 view-names 지정
    prefix: classpath:templates/
    suffix: .html #파일 수정시 반영하려면 하면 재시작을 해줘야 한다. 브라우저 새로고침시 수정사항 반영을 취해 cache=false 설정(운영시 true)
    cache: false
    check-template-location: true
    mode: HTML5
    order: 0

  datasource: #DB 접속정보
    data: classpath:insert.sql
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/db_eumong?characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      username: root
      password: gogo1103

  hikari: #Hikari 설정
    maximum-pool-size: 10 #connection-test-query: SELECT 1
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true

  jpa: #JPA 설정
    format_sql: true #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
    use_sql_comments: true
    show_sql: true #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
    hibernate: #방언 설정
      dialect: org.hibernate.dialect.MariaDBDialect #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
      ddl-auto: update

  log4jdbc: #log4jdbc 설정
    spylogdelegator:
      name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
    dump:
      sql:
        maxlinelength: 0

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache=false: false

  logging: # ROOT레벨 전체 로깅 레벨 결정
    level:
      root: info
      com.eumong.webservice.test: info
      com.eumong.webservice.test.controller: debug
